server {
    listen 80;
    server_name localhost;

    absolute_redirect off;
    port_in_redirect off;

    # Nginx settings for serving the Vite build with base: '/travel-brochure/'
    location /travel-brochure {
        alias /usr/share/nginx/html/travel-brochure;
        index index.html;
        try_files $uri $uri/ /travel-brochure/index.html;
    }

    # Redirect root to /travel-brochure/
    location = / {
        return 301 /travel-brochure/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
